### ISSUE TITLE
Nuxt 3 version of this template?

### ISSUE THREAD

**Issue by vesper8** [RSurya99/nefa#14]
Really love this template! It would be so useful however if you could release a Nuxt 3 version. I am reluctant to use it because I am already so used to using Vue 3 and this template uses Vue 2 / Nuxt 2.

Any chance this might be coming soon?

Thanks!!

**Comment by RSurya99** [comment]
This is my old project when I was still learning nuxt, maybe in my free time I would like to rebuild it if there is a lot of request.
